# Build from AMD's official PyTorch on ROCm image
FROM docker.io/rocm/pytorch:latest

# Update packages and install required dependencies
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y ffmpeg

# Since we do not need root anymore, switch to normal user
RUN useradd -m builder
USER builder
WORKDIR /home/builder
